version: '3.4'

x-base:
  &base
  networks:
    - net
  restart: always


services:
  fusionauth:
    <<: *base
    build: ./containers/fusionauth
    ports:
      - "9011:9011"
    env_file:
      - .env
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/fusionauth_db
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
    depends_on:
      - postgres

  node_api:
    <<: *base
    build: ./containers/node-api
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - ./api-gateway/app:/app
      - ./api-gateway/app/dist:/dist
      - ./api-gateway/app/node_modules:/node_modules
    env_file:
      - .env
    mem_reservation: 128m
    mem_limit: 1g

  node_schedule:
    <<: *base
    build: ./containers/node-schedule
    ports:
      - '127.0.0.1:8082:8082'
    volumes:
      - ./schedule/app:/app
      - ./schedule/app/dist:/app/dist
      - ./schedule/app/node_modules:/node_modules
    env_file:
      - .env
    mem_reservation: 128m

  postgres:
    <<: *base
    build: ./containers/postgres
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres/db_backups:/backups
      - ./postgres/pg:/var/lib/postgresql/data
    mem_reservation: 128m

  nginx:
    <<: *base
    build: ./containers/nginx
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - ./api-gateway/app:/app
    command: nginx -g "daemon off;"
    depends_on:
      - node_api
      - node_schedule
    mem_reservation: 20m
    mem_limit: 512m

networks:
  net:
    driver: bridge